name: CI/CD DevOps TP2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: tpdevops
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Wait for MariaDB to be healthy
      run: |
        echo "Waiting for MariaDB..."
        sleep 20

    - name: Seed database
      run: node fixtures/seed.js

    - name: Run unit tests
      run: npm test

    - name: Run Cypress E2E tests
      run: npx cypress run
